#!/bin/bash
# Generated link cleanup script

echo 'Broken links found in the following files:'
echo '  docs\index.md:'
echo '    Line 0: [Cyclical Documentation Transformation Protocol](Future_State_Data_Product/ai-prompts/Cyclical%20Documentation%20Transformation%20Protocol.md)'

echo '  docs\Future_State_Data_Product\ai-prompts\Towne Park Documentation Transformation - Enhanced AI Prompt.md:'
echo '    Line 0: [New System Document](Future_State_Data_Product/systems/billing/new-document.md)'
echo '    Line 0: [New System Document](Future_State_Data_Product/systems/billing/new-document.md)'
echo '    Line 0: [:octicons-arrow-right-24: New Business Rule](Future_State_Data_Product/business-rules/domain/new-rule.md)'
echo '    Line 0: [New Technical Doc](Future_State_Data_Product/technical/component/new-spec.md)'
echo '    Line 0: [New Document](path/to/document.md)'
echo '    Line 0: [PowerBill Overview](Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [PowerBill Overview](Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [PowerBill Overview](Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [Forecasting Data Sources](Future_State_Data_Product/technical/database/20250716_Forecasting_DataSources_TechnicalSpec.md)'
echo '    Line 0: [Forecasting Data Sources](Future_State_Data_Product/technical/database/20250716_Forecasting_DataSources_TechnicalSpec.md)'
echo '    Line 0: [ROI Analysis](Future_State_Data_Product/business-rules/billing/20250716_Billing_ROIAnalysis_SuccessMetrics.md)'
echo '    Line 0: [ROI Analysis](Future_State_Data_Product/business-rules/billing/20250716_Billing_ROIAnalysis_SuccessMetrics.md)'

echo '  docs\Future_State_Data_Product\ai-prompts\Towne Park Documentation Transformation - Ongoing Rule.md:'
echo '    Line 0: [PowerBill Overview](Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [PowerBill Overview](Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [PowerBill Overview](Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'

echo '  docs\Future_State_Data_Product\configuration\overview.md:'
echo '    Line 0: [Customer Site Configuration](customer-sites/index.md)'
echo '    Line 0: [Role-Based Permissions](../business-rules/user-access/role-based-permissions.md)'

echo '  docs\Future_State_Data_Product\standards\documentation-link-validation-process.md:'
echo '    Line 0: [Document Name](relative/path/to/document.md)'
echo '    Line 0: [Document Name](relative/path/to/document.md)'
echo '    Line 0: [Documentation Standards](documentation-standards.md)'
echo '    Line 0: [Quality Assurance Process](quality-assurance-process.md)'
echo '    Line 0: [MkDocs Configuration](../configuration/mkdocs-configuration.md)'

echo '  docs\Future_State_Data_Product\technical\index.md:'
echo '    Line 0: [Technical Specifications](specifications/index.md)'

echo '  docs\Future_State_Data_Product\user-processes\index.md:'
echo '    Line 0: [Billing Workflows](billing-admin/billing-workflows.md)'
echo '    Line 0: [Contract Admin](contract-admin/index.md)'
echo '    Line 0: [Site Admin](site-admin/index.md)'
echo '    Line 0: [Contact Management Procedures](site-admin/contact-management-procedures.md)'
echo '    Line 0: [Forecasting User Processes](forecasting/index.md)'

echo '  docs\Future_State_Data_Product\user-processes\account-manager\20250716_Forecasting_DataTableEditing_UserProcess.md:'
echo '    Line 0: [Billable Accounts Business Rules](../business-rules/forecasting/20250716_Forecasting_BillableAccounts_BusinessRules.md)'
echo '    Line 0: [Forecasting Technical Specifications](../technical/database/20250716_Forecasting_BillableAccounts_TechnicalSpec.md)'
echo '    Line 0: [District Manager Review Process](../user-processes/district-manager/forecasting-review.md)'
echo '    Line 0: [System Configuration Guide](../configuration/forecasting/data-table-configuration.md)'

echo '  docs\Future_State_Data_Product\user-processes\account-manager\20250716_Forecasting_StatisticsPagination_UserProcess.md:'
echo '    Line 0: [System Performance Guidelines](../../technical/performance/system-performance-guidelines.md)'

echo '  docs\Future_State_Data_Product\user-processes\account-manager\20250718_Forecasting_UserProcesses_AccountManagerWorkflows.md:'
echo '    Line 0: [Forecasting System Overview](../systems/forecasting/20250716_Forecasting_SystemOverview_Integrated.md)'
echo '    Line 0: [Customer Site Management](../systems/customer-sites/customer-site-directory.md)'

echo '  docs\Future_State_Data_Product\user-processes\account-manager\overview.md:'
echo '    Line 0: [Forecasting User Processes](../forecasting/index.md)'
echo '    Line 0: [Forecasting System Documentation](../../systems/forecasting/index.md)'

echo '  docs\Future_State_Data_Product\user-processes\billing-admin\20250702_Billing_AccountValidation_UserProcess.md:'
echo '    Line 0: [Batch Processing Configuration Guide](../../configuration/billing/batch-processing-configuration.md)'

echo '  docs\Future_State_Data_Product\user-processes\billing-admin\20250718_Billing_UATUserStories_ComprehensiveFeedback.md:'
echo '    Line 0: [Billing System Overview](../systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'

echo '  docs\Future_State_Data_Product\user-processes\billing-admin\overview.md:'
echo '    Line 0: [Billing System Documentation](../../systems/billing/index.md)'

echo '  docs\Future_State_Data_Product\user-processes\district-manager\overview.md:'
echo '    Line 0: [Forecasting User Processes](../forecasting/index.md)'

echo '  docs\Future_State_Data_Product\user-processes\forecasting\20250717_Forecasting_UserProcesses_Sprint26Features.md:'
echo '    Line 0: [Forecasting Technical Specifications](../technical/forecasting/20250717_Forecasting_TechnicalSpec_Sprint26Features.md)'
echo '    Line 0: [Business Rules Documentation](../business-rules/forecasting/20250717_Forecasting_BusinessRules_Sprint26Features.md)'
echo '    Line 0: [System Integration Guide](../systems/forecasting/integration-guide.md)'
echo '    Line 0: [Data Management Processes](../data-management/forecasting-data-processes.md)'
echo '    Line 0: [Quality Assurance Procedures](../quality-assurance/forecasting-qa-procedures.md)'
echo '    Line 0: [Training Materials](../training/forecasting-user-training.md)'

echo '  docs\Future_State_Data_Product\user-processes\forecasting\20250718_Forecasting_UserExperience_DesignDecisions.md:'
echo '    Line 0: [Account Manager Forecasting Workflows](20250718_Forecasting_UserProcesses_AccountManagerWorkflows.md)'

echo '  docs\Future_State_Data_Product\user-processes\forecasting\overview.md:'
echo '    Line 0: [Forecasting User Processes Index](index.md)'
echo '    Line 0: [Forecasting System Documentation](../../systems/forecasting/index.md)'

echo '  docs\Future_State_Data_Product\user-processes\site-admin\site-onboarding-workflow.md:'
echo '    Line 0: [Territory Assignment Rules](../../business-rules/customer-sites/territory-assignment-rules.md)'
echo '    Line 0: [Contact Management Rules](../../business-rules/customer-sites/contact-management-rules.md)'
echo '    Line 0: [Site Management API Specification](../../technical/api/customer-sites-api-spec.md)'
echo '    Line 0: [Contact Management Procedures](contact-management-procedures.md)'
echo '    Line 0: [Territory Management Procedures](../territory-admin/territory-management-procedures.md)'
echo '    Line 0: [Site Data Maintenance Procedures](site-data-maintenance-procedures.md)'
echo '    Line 0: [Territory Configuration Guide](../../configuration/customer-sites/territory-configuration-guide.md)'
echo '    Line 0: [Integration Configuration Guide](../../configuration/customer-sites/integration-configuration-guide.md)'
echo '    Line 0: [Billing System Integration](../../technical/integration/customer-sites-billing-integration.md)'
echo '    Line 0: [Forecasting Data Integration](../../technical/integration/customer-sites-forecasting-integration.md)'
echo '    Line 0: [Site Administrator Training Guide](../../training/site-admin/site-administrator-training.md)'
echo '    Line 0: [Onboarding Troubleshooting Guide](../../support/onboarding-troubleshooting.md)'

echo '  docs\Future_State_Data_Product\technical\backend\20250718_Architecture_ALMStrategy_PowerPlatform.md:'
echo '    Line 0: [Power Platform Licensing Analysis](../configuration/20250718_Architecture_LicensingAnalysis_PowerPlatform.md)'
echo '    Line 0: [Architecture Team Meeting Notes](../../team-notes/20250718_Architecture_TeamMeetingNotes_WeeklySync.md)'

echo '  docs\Future_State_Data_Product\technical\backend\20250718_Development_AIIntegration_TechnicalSpec.md:'
echo '    Line 0: [Code Validation Patterns](../../ai-prompts/Code%20Validation%20Patterns%20and%20Examples.md)'
echo '    Line 0: [Cyclical Documentation Transformation Protocol](../../ai-prompts/Cyclical%20Documentation%20Transformation%20Protocol.md)'
echo '    Line 0: [Enhanced AI Prompt](../../ai-prompts/Towne%20Park%20Documentation%20Transformation%20-%20Enhanced%20AI%20Prompt.md)'

echo '  docs\Future_State_Data_Product\technical\database\20250716_Forecasting_BillableAccounts_TechnicalSpec.md:'
echo '    Line 0: [PowerBill Integration Specifications](../integrations/powerbill-integration.md)'
echo '    Line 0: [Dataverse Forecast Integration Specifications](../integrations/dataverse-integration.md)'

echo '  docs\Future_State_Data_Product\technical\database\20250718_Contracts_DataDictionary_TechnicalSpec.md:'
echo '    Line 0: [Contract Management System Overview](../systems/contracts/20250716_Contracts_SystemOverview_PowerBill.md)'
echo '    Line 0: [PowerBill System Overview](../systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'

echo '  docs\Future_State_Data_Product\technical\database\20250718_Forecasting_DatabaseIntegration_TechnicalSpec.md:'
echo '    Line 0: [Forecasting Business Rules](../business-rules/forecasting/20250718_Forecasting_BusinessRules_CalculationsAndValidations.md)'
echo '    Line 0: [Account Manager User Processes](../user-processes/account-manager/20250718_Forecasting_UserProcesses_AccountManagerWorkflows.md)'

echo '  docs\Future_State_Data_Product\technical\database\customer-sites-data-schema.md:'
echo '    Line 0: [Territory Assignment Rules](../../business-rules/customer-sites/territory-assignment-rules.md)'
echo '    Line 0: [Contact Management Procedures](../../user-processes/site-admin/contact-management-procedures.md)'
echo '    Line 0: [Territory Configuration Guide](../../configuration/customer-sites/territory-configuration-guide.md)'
echo '    Line 0: [Customer Site API Specification](../api/customer-sites-api-spec.md)'
echo '    Line 0: [Billing System Integration](../integration/customer-sites-billing-integration.md)'
echo '    Line 0: [Forecasting Data Integration](../integration/customer-sites-forecasting-integration.md)'

echo '  docs\Future_State_Data_Product\technical\forecasting\20250702_Forecasting_DataIntegration_TechnicalSpec.md:'
echo '    Line 0: [Forecasting System Overview](../systems/forecasting/20250716_Forecasting_SystemOverview_Integrated.md)'
echo '    Line 0: [Job Group Management User Process](../user-processes/forecasting/20250702_Forecasting_JobGroupManagement_UserProcess.md)'
echo '    Line 0: [Forecasting Data Sources Technical Specification](../technical/database/20250716_Forecasting_DataSources_TechnicalSpec.md)'
echo '    Line 0: [Customer Site Management](../systems/customer-sites/customer-site-directory.md)'

echo '  docs\Future_State_Data_Product\technical\forecasting\20250718_Forecasting_BillableAccounts_TechnicalSpec.md:'
echo '    Line 0: [Forecasting Database Integration](../../database/20250718_Forecasting_DatabaseIntegration_TechnicalSpec.md)'
echo '    Line 0: [Forecasting Data Sources](../../database/20250716_Forecasting_DataSources_TechnicalSpec.md)'
echo '    Line 0: [Billable Accounts Technical Spec](../../database/20250716_Forecasting_BillableAccounts_TechnicalSpec.md)'
echo '    Line 0: [AI Integration Technical Spec](../../backend/20250718_Development_AIIntegration_TechnicalSpec.md)'
echo '    Line 0: [Power Platform ALM Strategy](../../backend/20250718_Architecture_ALMStrategy_PowerPlatform.md)'

echo '  docs\Future_State_Data_Product\technical\forecasting\index.md:'
echo '    Line 0: [User Processes](../../user-processes/forecasting/index.md)'

echo '  docs\Future_State_Data_Product\technical\integrations\20250718_Architecture_IntegrationStrategy_HybridConnections.md:'
echo '    Line 0: [Architecture Team Meeting Notes](../../team-notes/20250718_Architecture_TeamMeetingNotes_WeeklySync.md)'

echo '  docs\Future_State_Data_Product\technical\specifications\forecasting-pl-view-technical-spec.md:'
echo '    Line 0: [Forecasting System Overview](../../systems/forecasting/forecasting-system-overview.md)'
echo '    Line 0: [PowerBill Integration](../integrations/powerbill-integration.md)'

echo '  docs\Future_State_Data_Product\technical\specifications\power-automate-retry-mechanisms.md:'
echo '    Line 0: [Power Platform Architecture](../architecture/power-platform-architecture.md)'
echo '    Line 0: [Error Handling Standards](../../standards/error-handling-standards.md)'
echo '    Line 0: [Monitoring and Alerting Guide](../../operations/monitoring-alerting-guide.md)'
echo '    Line 0: [System Resilience Guidelines](../../standards/system-resilience-guidelines.md)'

echo '  docs\Future_State_Data_Product\technical\specifications\sharepoint-delta-token-management.md:'
echo '    Line 0: [SharePoint Integration Architecture](../architecture/sharepoint-integration-architecture.md)'
echo '    Line 0: [RSS System Overview](../../systems/rss/rss-system-overview.md)'
echo '    Line 0: [Data Synchronization Standards](../../standards/data-synchronization-standards.md)'
echo '    Line 0: [Error Handling Guidelines](../../standards/error-handling-guidelines.md)'

echo '  docs\Future_State_Data_Product\systems\contracts\20250716_Contracts_SystemOverview_PowerBill.md:'
echo '    Line 0: [Contract Escalation Business Rules](../business-rules/contracts/contract-escalation-rules.md)'
echo '    Line 0: [Contract Data Schema Technical Specification](../technical/database/contracts-data-schema.md)'
echo '    Line 0: [Contract Setup User Process](../user-processes/contract-admin/contract-setup-workflow.md)'
echo '    Line 0: [Contract Configuration Guide](../configuration/contracts/contract-configuration-guide.md)'
echo '    Line 0: [Billing System Integration](../systems/billing/billing-system-integration.md)'

echo '  docs\Future_State_Data_Product\systems\contracts\overview.md:'
echo '    Line 0: [Contract Management Index](index.md)'
echo '    Line 0: [Contract Configuration](../../configuration/contracts/index.md)'
echo '    Line 0: [Contract User Processes](../../user-processes/contract-admin/index.md)'

echo '  docs\Future_State_Data_Product\systems\customer-sites\20250716_CustomerSites_SystemOverview_Management.md:'
echo '    Line 0: [Territory Management Workflows](../user-processes/territory-admin/territory-management.md)'
echo '    Line 0: [Territory Assignment Rules](../../business-rules/customer-sites/territory-assignment-rules.md)'
echo '    Line 0: [Capacity Management Rules](../../business-rules/customer-sites/capacity-management-rules.md)'
echo '    Line 0: [Site Management API Specification](../../technical/api/customer-sites-api-spec.md)'
echo '    Line 0: [Contact Management Procedures](../../user-processes/site-admin/contact-management-procedures.md)'
echo '    Line 0: [Territory Reporting Procedures](../../user-processes/territory-admin/territory-reporting-procedures.md)'
echo '    Line 0: [Territory Configuration Guide](../../configuration/customer-sites/territory-configuration-guide.md)'
echo '    Line 0: [Billing System Integration](../../technical/integration/customer-sites-billing-integration.md)'
echo '    Line 0: [Forecasting Data Integration](../../technical/integration/customer-sites-forecasting-integration.md)'

echo '  docs\Future_State_Data_Product\systems\customer-sites\overview.md:'
echo '    Line 0: [Customer Sites Index](index.md)'
echo '    Line 0: [Site Admin User Processes](../../user-processes/site-admin/index.md)'
echo '    Line 0: [Customer Sites Configuration](../../configuration/customer-sites/index.md)'
echo '    Line 0: [Business Rules Documentation](../../business-rules/customer-sites/index.md)'

echo '  docs\Future_State_Data_Product\systems\forecasting\20250716_Forecasting_PayrollForecasting_SystemOverview.md:'
echo '    Line 0: [Billable Accounts Business Rules](../business-rules/forecasting/20250716_Forecasting_BillableAccounts_BusinessRules.md)'
echo '    Line 0: [Forecasting Technical Specifications](../technical/database/20250716_Forecasting_BillableAccounts_TechnicalSpec.md)'
echo '    Line 0: [Data Table Editing User Process](../user-processes/account-manager/20250716_Forecasting_DataTableEditing_UserProcess.md)'
echo '    Line 0: [Legion Integration Specifications](../technical/integrations/legion-integration.md)'
echo '    Line 0: [EDW Budget Integration](../technical/integrations/budget-integration.md)'

echo '  docs\Future_State_Data_Product\systems\forecasting\overview.md:'
echo '    Line 0: [Forecasting User Processes](../../user-processes/forecasting/index.md)'

echo '  docs\Future_State_Data_Product\configuration\customer-sites\site-setup-configuration.md:'
echo '    Line 0: [Territory Assignment Rules](../../business-rules/customer-sites/territory-assignment-rules.md)'
echo '    Line 0: [Contact Management Rules](../../business-rules/customer-sites/contact-management-rules.md)'
echo '    Line 0: [Site Management API Specification](../../technical/api/customer-sites-api-spec.md)'
echo '    Line 0: [Contact Management Procedures](../../user-processes/site-admin/contact-management-procedures.md)'
echo '    Line 0: [Territory Management Procedures](../../user-processes/territory-admin/territory-management-procedures.md)'
echo '    Line 0: [Territory Configuration Guide](territory-configuration-guide.md)'
echo '    Line 0: [Integration Configuration Guide](integration-configuration-guide.md)'
echo '    Line 0: [Security Configuration Guide](security-configuration-guide.md)'
echo '    Line 0: [Billing System Integration](../../technical/integration/customer-sites-billing-integration.md)'
echo '    Line 0: [Forecasting Data Integration](../../technical/integration/customer-sites-forecasting-integration.md)'
echo '    Line 0: [System Administration Guide](../../administration/system-administration-guide.md)'
echo '    Line 0: [Configuration Management Procedures](../../administration/configuration-management-procedures.md)'
echo '    Line 0: [Environment Management Guide](../../administration/environment-management-guide.md)'

echo '  docs\Future_State_Data_Product\configuration\system-settings\20250718_Architecture_LicensingAnalysis_PowerPlatform.md:'
echo '    Line 0: [Architecture Team Meeting Notes](../../team-notes/20250718_Architecture_TeamMeetingNotes_WeeklySync.md)'

echo '  docs\Future_State_Data_Product\configuration\system-settings\20250718_Development_DefinitionOfDone_ComprehensiveGuide.md:'
echo '    Line 0: [Code Validation Analysis](../../../20250716_Contracts_CodeValidation_Analysis.md)'

echo '  docs\Future_State_Data_Product\business-rules\billing\20250702_Billing_AccountValidation_BusinessRules.md:'
echo '    Line 0: [Financial Controls and Compliance](../../configuration/billing/financial-controls-configuration.md)'

echo '  docs\Future_State_Data_Product\business-rules\billing\20250717_Billing_ROIAnalysis_PowerBillSuccessMetrics.md:'
echo '    Line 0: [PowerBill System Overview](../systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [Billing System Generate Invoices](../systems/billing/generate-invoices.md)'
echo '    Line 0: [PLH Rate Escalation](../business-rules/contracts/plh-rate-escalation.md)'
echo '    Line 0: [Service Fee Escalation ECI](../business-rules/contracts/service-fee-escalation-eci.md)'
echo '    Line 0: [Billing Admin Generate Invoices](../user-processes/billing-admin/generate-invoices.md)'
echo '    Line 0: [Forecasting Data Sources Technical Spec](../technical/database/20250716_Forecasting_DataSources_TechnicalSpec.md)'
echo '    Line 0: [Development Configuration Guide Standards](../configuration/system-settings/20250716_Development_ConfigurationGuide_Standards.md)'

echo '  docs\Future_State_Data_Product\business-rules\billing\20250717_TownePark_CaseStudy_BillingSystemModernization.md:'
echo '    Line 0: [PowerBill System Overview](../systems/billing/20250716_Billing_SystemOverview_PowerBill.md)'
echo '    Line 0: [Billing Business Rules](../business-rules/billing/20250716_Billing_ROIAnalysis_SuccessMetrics.md)'
echo '    Line 0: [Revenue Share Calculations](../business-rules/contracts/service-fee-escalation-eci.md)'
echo '    Line 0: [Forecasting Data Sources](../technical/database/20250716_Forecasting_DataSources_TechnicalSpec.md)'
echo '    Line 0: [System Configuration Guide](../configuration/system-settings/20250716_Development_ConfigurationGuide_Standards.md)'
echo '    Line 0: [Customer Site Management](../systems/customer-sites/customer-site-directory.md)'
echo '    Line 0: [Invoice Generation Process](../user-processes/billing-admin/generate-invoices.md)'
echo '    Line 0: [Contract Administration](../business-rules/contracts/plh-rate-escalation.md)'
echo '    Line 0: [Forecasting System Overview](../systems/forecasting/20250716_Forecasting_SystemOverview_Integrated.md)'

echo '  docs\Future_State_Data_Product\business-rules\billing\negative-invoice-gl-entity-mapping.md:'
echo '    Line 0: [Great Plains Integration Technical Specification](../../technical/integrations/great-plains-integration-spec.md)'
echo '    Line 0: [Billing Process Workflows](../../user-processes/billing-admin/billing-workflows.md)'

echo '  docs\Future_State_Data_Product\business-rules\billing\overview.md:'
echo '    Line 0: [Billing System Documentation](../../systems/billing/index.md)'

echo '  docs\Future_State_Data_Product\business-rules\contracts\20250716_Contracts_BusinessRules_Comprehensive.md:'
echo '    Line 0: [Revenue Share Contract Configuration](../configuration/contracts/revenue-share-setup.md)'
echo '    Line 0: [Management Agreement Setup Guide](../configuration/contracts/management-agreement-setup.md)'
echo '    Line 0: [Per Labor Hour Configuration](../configuration/contracts/per-labor-hour-setup.md)'
echo '    Line 0: [Fixed Fee Contract Setup](../configuration/contracts/fixed-fee-setup.md)'
echo '    Line 0: [Forecasting Business Rules](../forecasting/forecasting-calculation-rules.md)'
echo '    Line 0: [GL Account Mapping Guide](../../technical/integrations/gl-account-mapping.md)'
echo '    Line 0: [Tax Calculation Rules](./tax-calculation-rules.md)'
echo '    Line 0: [Invoice Generation Process](../../user-processes/billing-admin/invoice-generation-workflow.md)'

echo '  docs\Future_State_Data_Product\business-rules\contracts\contract-escalation-rules.md:'
echo '    Line 0: [Contract Management System Overview](../systems/contracts/20250716_Contracts_SystemOverview_PowerBill.md)'
echo '    Line 0: [Contract Data Schema Technical Specification](../technical/database/contracts-data-schema.md)'
echo '    Line 0: [Escalation Processing User Guide](../user-processes/contract-admin/escalation-processing.md)'
echo '    Line 0: [Escalation Configuration Guide](../configuration/contracts/escalation-configuration.md)'

echo '  docs\Future_State_Data_Product\business-rules\contracts\overview.md:'
echo '    Line 0: [Contract Systems](../../systems/contracts/index.md)'
echo '    Line 0: [Contract User Processes](../../user-processes/contract-admin/index.md)'
echo '    Line 0: [Contract Configuration](../../configuration/contracts/index.md)'

echo '  docs\Future_State_Data_Product\business-rules\customer-sites\site-classification-rules.md:'
echo '    Line 0: [Site Management API Specification](../../technical/api/customer-sites-api-spec.md)'
echo '    Line 0: [Territory Management Procedures](../../user-processes/territory-admin/territory-management-procedures.md)'
echo '    Line 0: [Contact Management Procedures](../../user-processes/site-admin/contact-management-procedures.md)'
echo '    Line 0: [Territory Configuration Guide](../../configuration/customer-sites/territory-configuration-guide.md)'
echo '    Line 0: [Territory Assignment Rules](territory-assignment-rules.md)'
echo '    Line 0: [Capacity Management Rules](capacity-management-rules.md)'
echo '    Line 0: [Billing System Integration](../../technical/integration/customer-sites-billing-integration.md)'
echo '    Line 0: [Forecasting Data Integration](../../technical/integration/customer-sites-forecasting-integration.md)'

echo '  docs\Future_State_Data_Product\business-rules\forecasting\20250702_Forecasting_JobCodeManagement_BusinessRules.md:'
echo '    Line 0: [Workforce Planning Configuration](../../configuration/forecasting/workforce-planning-configuration.md)'

echo '  docs\Future_State_Data_Product\business-rules\forecasting\20250716_Forecasting_BillableAccounts_BusinessRules.md:'
echo '    Line 0: [Payroll Forecasting Rules](payroll-forecasting-business-rules.md)'
echo '    Line 0: [Budget Integration Rules](budget-integration-business-rules.md)'

echo '  docs\Future_State_Data_Product\business-rules\forecasting\20250717_Forecasting_BusinessRules_Sprint26Features.md:'
echo '    Line 0: [Forecasting Technical Specifications](../technical/forecasting/20250717_Forecasting_TechnicalSpec_Sprint26Features.md)'
echo '    Line 0: [User Process Documentation](../user-processes/forecasting/20250717_Forecasting_UserProcesses_Sprint26Features.md)'
echo '    Line 0: [System Integration Guide](../systems/forecasting/integration-guide.md)'
echo '    Line 0: [Forecasting System Overview](../systems/forecasting/forecasting-system-overview.md)'
echo '    Line 0: [Data Quality Standards](../standards/data-quality-standards.md)'
echo '    Line 0: [Financial Reporting Guidelines](../standards/financial-reporting-guidelines.md)'
echo '    Line 0: [Monitoring and Alerting Guide](../operations/monitoring-alerting-guide.md)'
echo '    Line 0: [Troubleshooting Procedures](../operations/troubleshooting-procedures.md)'
echo '    Line 0: [Performance Optimization Guide](../operations/performance-optimization-guide.md)'

echo '  docs\Future_State_Data_Product\business-rules\forecasting\20250718_Forecasting_BusinessRules_CalculationsAndValidations.md:'
echo '    Line 0: [Account Manager User Processes](../user-processes/account-manager/20250718_Forecasting_UserProcesses_AccountManagerWorkflows.md)'

echo '  docs\Future_State_Data_Product\business-rules\forecasting\index.md:'
echo '    Line 0: [User Processes](../../user-processes/forecasting/index.md)'

echo '  docs\Future_State_Data_Product\business-rules\forecasting\overview.md:'
echo '    Line 0: [Forecasting System Documentation](../../systems/forecasting/index.md)'
echo '    Line 0: [Forecasting User Processes](../../user-processes/forecasting/index.md)'
