site_name: Towne Park Data Product
site_url: http://example.org/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search
  - git-revision-date-localized
  - macros

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - admonition
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Documentation Overview: Future_State_Data_Product/README.md
  - TP Product Roadmap: Future_State_Data_Product/TP Product Roadmap.md
  - Transformation Session Log: Future_State_Data_Product/20250716_Transformation_Session_Log.md
  - Code Validation Analysis: Future_State_Data_Product/20250716_Contracts_CodeValidation_Analysis.md
  - AI Prompts:
    - Enhanced AI Prompt: Future_State_Data_Product/ai-prompts/Towne Park Documentation Transformation - Enhanced AI Prompt.md
    - Ongoing Rule: Future_State_Data_Product/ai-prompts/Towne Park Documentation Transformation - Ongoing Rule.md
    - Cyclical Transformation Protocol: Future_State_Data_Product/ai-prompts/Cyclical Documentation Transformation Protocol.md
    - Code Validation Patterns: Future_State_Data_Product/ai-prompts/Code Validation Patterns and Examples.md
    - Code Validation Maintenance: Future_State_Data_Product/ai-prompts/Code Validation Maintenance Procedures.md
  - Systems:
    - Billing:
      - Overview: Future_State_Data_Product/systems/billing/overview.md
      - PowerBill System Overview: Future_State_Data_Product/systems/billing/20250716_Billing_SystemOverview_PowerBill.md
      - PowerBill System Overview (Detailed): Future_State_Data_Product/systems/billing/powerbill-system-overview.md
      - Architecture: Future_State_Data_Product/systems/billing/architecture.md
      - Integrations: Future_State_Data_Product/systems/billing/integrations.md
      - Generate Invoices: Future_State_Data_Product/systems/billing/generate-invoices.md
    - Forecasting:
      - Overview: Future_State_Data_Product/systems/forecasting/overview.md
      - Comprehensive Master Overview: Future_State_Data_Product/systems/forecasting/20250718_Forecasting_SystemOverview_ComprehensiveMaster.md
      - Project Discovery: Future_State_Data_Product/systems/forecasting/20250716_Forecasting_SystemOverview_Discovery.md
      - Master Architecture: Future_State_Data_Product/systems/forecasting/20250716_Forecasting_SystemOverview_MasterArchitecture.md
      - Integrated System Overview: Future_State_Data_Product/systems/forecasting/20250716_Forecasting_SystemOverview_Integrated.md
      - Payroll Forecasting System: Future_State_Data_Product/systems/forecasting/20250716_Forecasting_PayrollForecasting_SystemOverview.md
      - Architecture: Future_State_Data_Product/systems/forecasting/architecture.md
      - Integrations: Future_State_Data_Product/systems/forecasting/integrations.md
    - Customer Sites:
      - Customer Site Directory: Future_State_Data_Product/systems/customer-sites/customer-site-directory.md
      - Customer Site Management System Overview: Future_State_Data_Product/systems/customer-sites/20250716_CustomerSites_SystemOverview_Management.md
    - Contracts:
      - Contract Management System Overview: Future_State_Data_Product/systems/contracts/20250716_Contracts_SystemOverview_PowerBill.md
  - Business Rules:
    - Contract Types:
      - Overview: Future_State_Data_Product/business-rules/contract-types/overview.md
      - Revenue Share: Future_State_Data_Product/business-rules/contract-types/revenue-share.md
      - Fixed Fee: Future_State_Data_Product/business-rules/contract-types/fixed-fee.md
      - Per Labor Hour: Future_State_Data_Product/business-rules/contract-types/per-labor-hour.md
      - Management Agreement: Future_State_Data_Product/business-rules/contract-types/management-agreement.md
    - Billing:
      - Overview: Future_State_Data_Product/business-rules/billing/overview.md
      - Invoice Calculation: Future_State_Data_Product/business-rules/billing/invoice-calculation.md
      - Validation: Future_State_Data_Product/business-rules/billing/validation.md
      - Bell Service Fee: Future_State_Data_Product/business-rules/billing/bell-service-fee.md
      - ROI Analysis & Success Metrics: Future_State_Data_Product/business-rules/billing/20250716_Billing_ROIAnalysis_SuccessMetrics.md
      - PowerBill ROI Analysis & Success Metrics: Future_State_Data_Product/business-rules/billing/20250717_Billing_ROIAnalysis_PowerBillSuccessMetrics.md
      - Billing System Modernization Case Study: Future_State_Data_Product/business-rules/billing/20250717_TownePark_CaseStudy_BillingSystemModernization.md
      - Negative Invoice GL Entity Mapping: Future_State_Data_Product/business-rules/billing/negative-invoice-gl-entity-mapping.md
      - Management Fee Escalation Rules: Future_State_Data_Product/business-rules/billing/management-fee-escalation-rules.md
      - PTEB Escalation Rules: Future_State_Data_Product/business-rules/billing/pteb-escalation-rules.md
      - Account Validation Business Rules: Future_State_Data_Product/business-rules/billing/20250702_Billing_AccountValidation_BusinessRules.md
    - Forecasting:
      - Overview: Future_State_Data_Product/business-rules/forecasting/overview.md
      - Calculations and Validations: Future_State_Data_Product/business-rules/forecasting/20250718_Forecasting_BusinessRules_CalculationsAndValidations.md
      - Development Decisions: Future_State_Data_Product/business-rules/forecasting/20250718_Forecasting_BusinessRules_DevelopmentDecisions.md
      - Process Workflow: Future_State_Data_Product/business-rules/forecasting/20250716_Forecasting_BusinessRules_ProcessWorkflow.md
      - Billable Accounts Business Rules: Future_State_Data_Product/business-rules/forecasting/20250716_Forecasting_BillableAccounts_BusinessRules.md
      - Sprint 26 Features Business Rules: Future_State_Data_Product/business-rules/forecasting/20250717_Forecasting_BusinessRules_Sprint26Features.md
      - Group Transient Logic: Future_State_Data_Product/business-rules/forecasting/group-transient-logic.md
      - Payroll: Future_State_Data_Product/business-rules/forecasting/payroll.md
      - Revenue: Future_State_Data_Product/business-rules/forecasting/revenue.md
      - Statistics: Future_State_Data_Product/business-rules/forecasting/statistics.md
      - Job Code Management Business Rules: Future_State_Data_Product/business-rules/forecasting/20250702_Forecasting_JobCodeManagement_BusinessRules.md
    - Contracts:
      - Comprehensive Business Rules: Future_State_Data_Product/business-rules/contracts/20250716_Contracts_BusinessRules_Comprehensive.md
      - Contract Escalation Rules: Future_State_Data_Product/business-rules/contracts/contract-escalation-rules.md
      - PLH Rate Escalation: Future_State_Data_Product/business-rules/contracts/plh-rate-escalation.md
      - Service Fee Escalation ECI: Future_State_Data_Product/business-rules/contracts/service-fee-escalation-eci.md
    - Customer Sites:
      - Site Classification Rules: Future_State_Data_Product/business-rules/customer-sites/site-classification-rules.md
  - Technical:
    - Overview: Future_State_Data_Product/technical/overview.md
    - Technical Documentation Index: Future_State_Data_Product/technical/index.md
    - Frontend: Future_State_Data_Product/technical/frontend/index.md
    - Backend:
      - Overview: Future_State_Data_Product/technical/backend/index.md
      - ALM Strategy for Power Platform: Future_State_Data_Product/technical/backend/20250718_Architecture_ALMStrategy_PowerPlatform.md
      - AI Integration Technical Spec: Future_State_Data_Product/technical/backend/20250718_Development_AIIntegration_TechnicalSpec.md
      - Forecasting Technical Architecture & API Design: Future_State_Data_Product/technical/backend/20250718_Forecasting_TechnicalArchitecture_APIDesign.md
      - Billing Architecture: Future_State_Data_Product/technical/backend/20250716_Billing_TechnicalArchitecture_Development.md
    - Database:
      - Overview: Future_State_Data_Product/technical/database/index.md
      - Forecasting Database Integration: Future_State_Data_Product/technical/database/20250718_Forecasting_DatabaseIntegration_TechnicalSpec.md
      - Forecasting Data Sources: Future_State_Data_Product/technical/database/20250716_Forecasting_DataSources_TechnicalSpec.md
      - Billable Accounts Technical Spec: Future_State_Data_Product/technical/database/20250716_Forecasting_BillableAccounts_TechnicalSpec.md
      - Contracts Data Dictionary Technical Spec: Future_State_Data_Product/technical/database/20250718_Contracts_DataDictionary_TechnicalSpec.md
      - Schema Design: Future_State_Data_Product/technical/database/schema-design.md
      - Contracts Data Schema: Future_State_Data_Product/technical/database/contracts-data-schema.md
      - Customer Sites Data Schema: Future_State_Data_Product/technical/database/customer-sites-data-schema.md
    - Forecasting:
      - Sprint 26 Features Technical Spec: Future_State_Data_Product/technical/forecasting/20250717_Forecasting_TechnicalSpec_Sprint26Features.md
      - Billable Accounts Technical Spec: Future_State_Data_Product/technical/forecasting/20250718_Forecasting_BillableAccounts_TechnicalSpec.md
      - Data Integration Technical Spec: Future_State_Data_Product/technical/forecasting/20250702_Forecasting_DataIntegration_TechnicalSpec.md
    - Specifications:
      - Forecasting P&L View Technical Spec: Future_State_Data_Product/technical/specifications/forecasting-pl-view-technical-spec.md
      - Power Automate Retry Mechanisms: Future_State_Data_Product/technical/specifications/power-automate-retry-mechanisms.md
      - SharePoint Delta Token Management: Future_State_Data_Product/technical/specifications/sharepoint-delta-token-management.md
    - Integrations:
      - Integration Strategy for Hybrid Connections: Future_State_Data_Product/technical/integrations/20250718_Architecture_IntegrationStrategy_HybridConnections.md
      - Great Plains Integration: Future_State_Data_Product/technical/integrations/great-plains-integration.md
      - Billing Integrations: Future_State_Data_Product/technical/integrations/billing-integrations.md
      - Budget Integration: Future_State_Data_Product/technical/integrations/budget-integration.md
      - Leads Integration: Future_State_Data_Product/technical/integrations/leads-integration.md
      - Legion Integration: Future_State_Data_Product/technical/integrations/legion-integration.md
  - User Processes:
    - Account Manager:
      - Overview: Future_State_Data_Product/user-processes/account-manager/index.md
      - Forecasting User Processes: Future_State_Data_Product/user-processes/account-manager/20250718_Forecasting_UserProcesses_AccountManagerWorkflows.md
      - Forecasting Methodology Interview Insights: Future_State_Data_Product/user-processes/account-manager/20250718_AccountManager_ForecastingMethodology_InterviewInsights.md
      - Data Table Editing Process: Future_State_Data_Product/user-processes/account-manager/20250716_Forecasting_DataTableEditing_UserProcess.md
      - Statistics Pagination Process: Future_State_Data_Product/user-processes/account-manager/20250716_Forecasting_StatisticsPagination_UserProcess.md
    - Billing Admin:
      - Overview: Future_State_Data_Product/user-processes/billing-admin/index.md
      - Generate Invoices: Future_State_Data_Product/user-processes/billing-admin/generate-invoices.md
      - Customer Migration: Future_State_Data_Product/user-processes/billing-admin/customer-migration.md
      - Account Validation User Process: Future_State_Data_Product/user-processes/billing-admin/20250702_Billing_AccountValidation_UserProcess.md
      - UAT User Stories Comprehensive Feedback: Future_State_Data_Product/user-processes/billing-admin/20250718_Billing_UATUserStories_ComprehensiveFeedback.md
    - Contract Admin:
      - Contract Setup Workflow: Future_State_Data_Product/user-processes/contract-admin/contract-setup-workflow.md
      - Contract Query Examples User Reference: Future_State_Data_Product/user-processes/contract-admin/20250718_Contracts_QueryExamples_UserReference.md
    - District Manager:
      - Overview: Future_State_Data_Product/user-processes/district-manager/index.md
      - Pilot & Rollout Process: Future_State_Data_Product/user-processes/district-manager/20250716_Forecasting_PilotRollout_ProcessWorkflow.md
    - Forecasting:
      - Overview: Future_State_Data_Product/user-processes/forecasting/overview.md
      - Forecasting User Processes Index: Future_State_Data_Product/user-processes/forecasting/index.md
      - Sprint 26 Features User Processes: Future_State_Data_Product/user-processes/forecasting/20250717_Forecasting_UserProcesses_Sprint26Features.md
      - User Experience Design Decisions: Future_State_Data_Product/user-processes/forecasting/20250718_Forecasting_UserExperience_DesignDecisions.md
      - Job Group Management User Process: Future_State_Data_Product/user-processes/forecasting/20250702_Forecasting_JobGroupManagement_UserProcess.md
    - Site Admin:
      - Site Onboarding Workflow: Future_State_Data_Product/user-processes/site-admin/site-onboarding-workflow.md
  - Configuration:
    - Contracts:
      - Contract Configuration Guide: Future_State_Data_Product/configuration/contracts/contract-configuration-guide.md
    - Customer Sites:
      - Site Setup Configuration: Future_State_Data_Product/configuration/customer-sites/site-setup-configuration.md
    - Contract Setup: Future_State_Data_Product/configuration/contract-setup/index.md
    - User Access:
      - Overview: Future_State_Data_Product/configuration/user-access/index.md
      - Role-Based Permissions: Future_State_Data_Product/configuration/user-access/role-based-permissions.md
    - System Settings:
      - Overview: Future_State_Data_Product/configuration/system-settings/index.md
      - System Configuration Overview: Future_State_Data_Product/configuration/system-settings/system-configuration-overview.md
      - Power Platform Licensing Analysis: Future_State_Data_Product/configuration/system-settings/20250718_Architecture_LicensingAnalysis_PowerPlatform.md
      - Development Standards: Future_State_Data_Product/configuration/system-settings/20250716_Development_ConfigurationGuide_Standards.md
      - Comprehensive Development Standards: Future_State_Data_Product/configuration/system-settings/20250718_Development_Standards_ComprehensiveGuide.md
      - Definition of Done Comprehensive Guide: Future_State_Data_Product/configuration/system-settings/20250718_Development_DefinitionOfDone_ComprehensiveGuide.md
      - Pull Request Review Guide: Future_State_Data_Product/configuration/system-settings/20250718_Development_PRReview_ComprehensiveGuide.md
  - Standards:
    - Overview: Future_State_Data_Product/standards/index.md
    - Data Quality Standards: Future_State_Data_Product/standards/data-quality-standards.md
  - Team Notes:
    - Jonathan Aulson Notes:
      - Architecture Team Meeting Notes: Future_State_Data_Product/team-notes/AulsonJonathan-Notes/20250718_Architecture_TeamMeetingNotes_WeeklySync.md
    - Development Team Notes:
      - Daily Scrum Team Notes: Future_State_Data_Product/team-notes/20250718_Development_DailyScrum_TeamNotes.md
      - Sprint Planning Project Management: Future_State_Data_Product/team-notes/20250718_Development_SprintPlanning_ProjectManagement.md
  - Glossary: Future_State_Data_Product/glossary.md
