site_name: Towne Park Data Product
site_url: https://jonathan-aulson.github.io/Data_Product_TownePark/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight

plugins:
  - search
  - git-revision-date-localized
  - mermaid2

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - admonition
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Financial Entities:
    - Business Rules:
      - Forecasting Data Validation Business Rules: knowledge-corpus/business-rules/forecasting-data-validation-business-rules.md
  - System Architecture:
    - EDW Integration Technical Specification: knowledge-corpus/technical-specifications/edw-integration-technical-specification.md
  - Role-Based Processes:
    - AI-Assisted Sprint Planning Process Guide: knowledge-corpus/user-processes/ai-assisted-sprint-planning-process-guide.md
  - Validation Reports:
    - Management Agreement Code Validation: knowledge-corpus/validation-reports/management-agreement-code-validation-report.md
  - Meeting Transcripts:
    - Sprint 28 Management Agreement Development: knowledge-corpus/meeting-transcripts/sprint28-management-agreement-development-meeting.md
    - Sprint 29 Budget vs Actuals Development: knowledge-corpus/meeting-transcripts/sprint29-budget-actuals-development-meeting.md
    - Sprint 30 Forecasting Variance Development: knowledge-corpus/meeting-transcripts/sprint30-forecasting-variance-development-meeting.md
    - Daily Scrum Development Progress: knowledge-corpus/meeting-transcripts/daily-scrum-development-progress-team-notes.md
  - Standards Framework:
    - AI Content Safety Checklist: knowledge-corpus/standards/ai-content-safety-checklist.md
  - Configuration Guides:
    - AI Development Tools Configuration Guide: knowledge-corpus/configuration/ai-development-tools-configuration-guide.md