# Project information
site_name: Towne Park Documentation
site_description: Comprehensive documentation for Towne Park financial systems
site_url: https://your-organization.github.io/Data_Product_TownePark/
site_author: Towne Park Team

# Repository
repo_name: jonathan-aulson/Data_Product_TownePark
repo_url: https://github.com/jonathan-aulson/Data_Product_TownePark
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Towne Park

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
  palette:
    # Use Towne Park colors here
    primary: indigo
    accent: indigo
  icon:
    logo: material/library
  language: en

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - footnotes
  - meta
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      type: date
  - minify:
      minify_html: true
  - macros

# Extra settings
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jonathan-aulson
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/allata

# Navigation
nav:
  - Home: /Future_State_Data_Product/docs/index.md
  - Systems:
    - Billing:
      - Overview: /Future_State_Data_Product/systems/billing/overview.md
      - Architecture: /Future_State_Data_Product/systems/billing/architecture.md
      - Integrations: /Future_State_Data_Product/systems/billing/integrations.md
    - Forecasting:
      - Overview: /Future_State_Data_Product/systems/forecasting/overview.md
      - Architecture: /Future_State_Data_Product/systems/forecasting/architecture.md
      - Integrations: /Future_State_Data_Product/systems/forecasting/integrations.md
  - Business Rules:
    - Contract Types:
      - Revenue Share: /Future_State_Data_Product/business-rules/contract-types/revenue-share.md
      - Fixed Fee: /Future_State_Data_Product/business-rules/contract-types/fixed-fee.md
      - Per Labor Hour: /Future_State_Data_Product/business-rules/contract-types/per-labor-hour.md
      - Management Agreement: /Future_State_Data_Product/business-rules/contract-types/management-agreement.md
    - Billing:
      - Invoice Calculation: /Future_State_Data_Product/business-rules/billing/invoice-calculation.md
      - Validation: /Future_State_Data_Product/business-rules/billing/validation.md
      - Bell Service Fee: /Future_State_Data_Product/business-rules/billing/bell-service-fee.md
    - Forecasting:
      - Payroll: /Future_State_Data_Product/business-rules/forecasting/payroll.md
      - Revenue: /Future_State_Data_Product/business-rules/forecasting/revenue.md
      - Statistics: /Future_State_Data_Product/business-rules/forecasting/statistics.md
  - Technical:
    - Frontend: /Future_State_Data_Product/technical/frontend/index.md
    - Backend: /Future_State_Data_Product/technical/backend/index.md
    - Database: /Future_State_Data_Product/technical/database/index.md
    - Integrations: /Future_State_Data_Product/technical/integrations/index.md
  - User Processes:
    - Account Manager: /Future_State_Data_Product/user-processes/account-manager/index.md
    - Billing Admin: /Future_State_Data_Product/user-processes/billing-admin/index.md
    - District Manager: /Future_State_Data_Product/user-processes/district-manager/index.md
  - Configuration:
    - Contract Setup: /Future_State_Data_Product/configuration/contract-setup/index.md
    - User Access: /Future_State_Data_Product/configuration/user-access/index.md
    - System Settings: /Future_State_Data_Product/configuration/system-settings/index.md
  - Glossary: /Future_State_Data_Product/glossary.md
