trigger:
- develop

variables:
  OutputFolder: 'packed'
  SourceFolder: '$(SolutionFolderName)'  

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerPlatformToolInstaller@2


- task: CmdLine@2
  displayName: 'CreateCustomZipFolder'
  inputs:
    script: |
      echo Zipping contents of $(SolutionFolderName)
      cd "$(Build.SourcesDirectory)\$(SolutionFolderName)"
      "C:\Program Files\7-Zip\7z.exe" a -tzip "$(Build.ArtifactStagingDirectory)\$(SolutionName).zip" * -mx=9

- task: PowerPlatformUnPackSolution@2
  inputs:
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName).zip'
    SolutionTargetFolder: '$(Build.ArtifactStagingDirectory)/solutions/$(SolutionName)'
    
- task: PowerPlatformPackSolution@2
  inputs:
    SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/solutions/$(SolutionName)_unmanaged.zip'
    SolutionSourceFolder: '$(Build.ArtifactStagingDirectory)/solutions/$(SolutionName)'
    solutionType: 'Unmanaged'
  
- task: PowerPlatformImportSolution@2
  inputs:
    authenticationType: 'PowerPlatformSPN'
    PowerPlatformSPN: '$(PowerPlatformEnvironment)'
    SolutionInputFile: '$(Build.ArtifactStagingDirectory)/solutions/$(SolutionName)_unmanaged.zip'
    AsyncOperation: true
    MaxAsyncWaitTime: '60'
    OverwriteUnmanagedCustomizations: true
    PublishWorkflows: true